spring:
  application:
    name: karate
  profiles:
    default: local

logging:
    root: INFO
#    jdbc.sqlonly: OFF
#    jdbc.sqltiming: INFO
#    jdbc.audit: OFF
#    jdbc.resultset: OFF
#    jdbc.connection: OFF
#    jdbc.resultsettable: INFO
    pattern:
      console:  "[%d{yyyy-MM-dd HH:mm:ss}] [%clr(%-5level)] [%clr(%logger{36})] - %clr(%msg%n)"

#스웨거 기본 경로를 설정
springdoc:
  swagger-ui:
    path: /swagger
#  use-fqn: true

server:
  port: 8081