spring:
  application:
    name: karate

logging:
  level:
    root: INFO
#    jdbc.sqlonly: OFF
#    jdbc.sqltiming: INFO
#    jdbc.audit: OFF
#    jdbc.resultset: OFF
#    jdbc.connection: OFF
#    jdbc.resultsettable: INFO
#  pattern:
#    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%clr(%-5level)] [%clr(%logger{36})] - %clr(%msg%n)"

server:
  port: 8081